# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "vboas/centos7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.provision "shell", path: "scripts/config_provision.sh"

  config.vbguest.auto_update = false
end
