# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "vboas/centos7"
    config.vm.hostname = "db01"
    config.vm.network "private_network", ip: "192.168.1.4"
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.provision "shell", path: "scripts/config_provision.sh"

    # Enable synced folder
    config.vm.synced_folder "../control-node/ssh_key", "/vagrant_ssh"

    config.vbguest.auto_update = false
  end
  